### PR TITLE
Added `AuthTokens` interface

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #7 
Added `AuthTokens` interface, class `TokenItem` to represent token and some tests.

### CODE REVIEW

**Review by genryxy — APPROVED** [review]
@olenagerasimova thanks, looks good to me

**Comment by olenagerasimova** [comment]
@g4s8 take a look/merge, please

**Comment by olenagerasimova** [comment]
@g4s8 ping

**Review by g4s8 — APPROVED** [review]
@olenagerasimova thanks

**Pull request merged**
